{% set name = "Gcluster" %}
{% set version = "2.0.3" %}
{% set sha256 = "7b3a0d465377e644614c8511045b743acece12a33c56ac356d3d7b931e85b525" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    url: https://github.com/Xiangyang1984/Gcluster/archive/Gcluster-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - mcl
    - blast
    - perl-gd
    - perl-gd-svg
    - perl-svg
    - perl-bioperl-core
    #- git
    
test:
  commands:
    - Gcluster -h
    - interested_gene_generation -h
    - blastp -h
    - makeblastdb -h
    - mcl --help

about:
  home: 'http://www.microbialgenomic.com/Gcluster_tool.html'
  summary: 'Gcluster is a simple-to-use tool for visualizing and comparing genome contexts for numerous genomes'
  license: perl_5
